title: "[Q&A]: "
labels:
  - question
body:
  - type: markdown
    attributes:
      value: Ask a question about the project.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: What I've tried
      description: Any research or attempts you've already made.
    validations:
      required: false
